[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmi = "0.31.2"
anyhow = "1.0.81"

[profile.wasm]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
inherits = "release"
