[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
anyhow = "1.0.81"
wasmi = "0.31.2"

[profile.release]
lto = "thin"
codegen-units = 1
# opt-level = 's'
opt-level = 'z'
