[toolchain]
channel = "nightly-2024-03-26"
components = [
    "cargo",
    "clippy",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
    "rust-analyzer",
]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
